version: '3'

services:
  ch_server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
      - ./ch_migrations:/var/lib/migrations
    networks:
      - ch_test_task

  ch_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
    networks:
      - ch_test_task

networks:
  ch_test_task:
    driver: bridge